lachelier/sugoroku

src/app/Models/Room.php

#4 Roomモデルの作成を行ったので、レビューのほうをよろしくお願いいたします。

#4 Roomモデルの作成

---

src/app/Http/Controllers/HomeController.php
src/composer.json
src/composer.lock
src/package.json
src/resources/js/app.js
src/resources/js/bootstrap.js
src/resources/js/components/ExampleComponent.vue
src/resources/sass/_variables.scss
src/resources/sass/app.scss
src/resources/views/auth/login.blade.php
src/resources/views/auth/passwords/confirm.blade.php
src/resources/views/auth/passwords/email.blade.php
src/resources/views/auth/passwords/reset.blade.php
src/resources/views/auth/register.blade.php
src/resources/views/auth/verify.blade.php
src/resources/views/home.blade.php
src/resources/views/layouts/app.blade.php
src/routes/web.php
src/webpack.mix.js

以下のIssueの対応です。
https://github.com/lachelier/sugoroku/issues/2
実際にRegisterでUser名、Email、Passwordを登録してログインするところまで画面で確認してます。

create authentication function

---

src/app/Repositories/RoomRepository.php

#5 RoomRepositoryクラスの作成を行ったので、レビューのほうをよろしくお願いいたします。

#5 RoomRepositoryクラスの作成

---

src/database/migrations/2020_05_13_153711_create_boards_table.php
src/database/migrations/2020_05_13_153740_create_rooms_table.php

#11 boardsテーブル、roomsテーブルのマイグレーション作成を行ったので、レビューのほうをよろしくお願いいたします。

#11 boardsテーブル、roomsテーブルのマイグレーション作成

---

src/.circleci/config.yml

https://github.com/lachelier/sugoroku/issues/14
一旦、作成しました〜！
よろしくお願いします🙇‍♂️

#14 CircleCIの設定ファイル作成

---

src/config/const.php

https://github.com/lachelier/sugoroku/issues/32

#32 コマのステータスを定義

---

src/config/const.php
src/database/seeds/BoardsTableSeeder.php
src/database/seeds/DatabaseSeeder.php

https://github.com/lachelier/sugoroku/issues/23

#23 Boardシーダクラスの定義

---

src/database/migrations/2020_05_16_041234_create_room_user_table.php

https://github.com/lachelier/sugoroku/issues/30

#30 room_userテーブルのマイグレーション作成

---

src/app/Http/Controllers/RoomController.php
src/app/Models/Room.php
src/app/Repositories/RoomRepository.php
src/resources/views/room/index.blade.php
src/tests/Feature/RoomTest.php

以下Issueの対応になります〜！
https://github.com/lachelier/sugoroku/issues/24

#24 オープン中の部屋一覧を表示

---

src/app/Models/Board.php
src/app/Models/User.php

以下Issueの対応しました〜！
https://github.com/lachelier/sugoroku/issues/21

#21 UserとBoardのリレーションを作成

---

src/app/Repositories/RoomRepository.php
src/tests/Feature/RoomTest.php

以下Issueの対応です！
https://github.com/lachelier/sugoroku/issues/48

#48 unameからRoomオブジェクトを取得できるメソッドを作成

---

src/resources/js/components/partials/createRoomModal.vue

#45 部屋作成時のエラーメッセージを表示の対応を行いましたので、ご確認をお願いいたします。
本当は部屋一覧に表示したかったのですが、アラート表示でも良いということだったので、アラート表示で対応いたしました。

#45 部屋作成時のエラーメッセージを表示

---

src/routes/web.php

#25 部屋ページのルーティング設定を行いましたので、ご確認をお願いいたします。

#25 部屋ページのルーティング設定

---

src/app/Models/Room.php
src/app/Repositories/RoomRepository.php
src/tests/Feature/RoomTest.php

https://github.com/lachelier/sugoroku/issues/33
後、修正に伴いRoomモデルのリレーション設定が一部間違ってたため修正しました。

#33 入室処理の作成

---

src/app/Repositories/RoomRepository.php
src/config/const.php

#51のissue対応
max_member_countを5で定義。createする際に定義したやつで作成するように変更

#51 🍒最大入室数を5人にする

---

src/app/Http/Controllers/RoomController.php
src/app/Repositories/RoomRepository.php
src/tests/Feature/RoomTest.php

https://github.com/lachelier/sugoroku/issues/36
後、RoomRepository.phpのcreate()で
初期値として$room->member_count = 1;となってたのでこれを0に修正しました。
理由：create()実行時点ではまだ入室は行われないため。

#36 部屋のオーナーを参加させる

---

src/app/Http/Controllers/RoomController.php
src/routes/web.php
src/tests/Feature/RoomTest.php

#65 ユーザーが部屋に参加できるページを作成するの実装とテストコード作成が完了いたしましたので、ご確認をお願いいたします。

#65 ユーザーが部屋に参加できるページを作成する

---

src/app/Http/Controllers/RoomController.php
src/app/Providers/RouteServiceProvider.php
src/routes/web.php
src/tests/Feature/RoomTest.php

https://github.com/lachelier/sugoroku/issues/64

#64 ログイン後のリダイレクト先を変更する

---

src/app/Repositories/RoomRepository.php
src/tests/Feature/RoomTest.php

以下Issueの対応になります🙌
https://github.com/lachelier/sugoroku/issues/70

#70 解散処理の実装

---

src/resources/views/room/index.blade.php

不要なファイルを除こうと努力してみたのですが、できたかどうか...。ブランチ名も新しいものを作ってしまいました。複雑にして申し訳ありません。index.blade.phpのみpushしてみたのですが、ご確認お願い致します。

条件分岐を参加ボタンに追加

---

src/app/Http/Controllers/RoomController.php
src/resources/js/components/partials/createRoomModal.vue
src/tests/Feature/RoomTest.php

毎度のことながらサポートいただきありがとうございます。
#50の対応が完了いたしましたので、ご確認をお願いいたします。

#50 部屋を作成後に、部屋ページにリダイレクトさせる 

---

src/database/migrations/2020_05_24_100031_create_room_logs_table.php

#98 room_logsテーブルのマイグレーション作成完了いたしましたので、ご確認をお願いいたします。

#98 room_logsテーブルのマイグレーション作成

---

src/resources/views/room/index.blade.php

index.blade.phpの参加ボタンにリンクを挿入してみました。ご確認、お願い致します。

参加ボタンにリンクを追加

---

src/config/const.php

config/const.php に
action_by_dice: 1
action_by_space: 2
を追加いたしました。
ご確認、お願い致します。

アクションIDの定義

---

src/app/Http/Controllers/SugorokuController.php
src/app/Repositories/RoomRepository.php
src/routes/api.php
src/tests/Feature/SugorokuTest.php

#93 コマの現在地を返すAPIを作成の実装が完了したのでご確認をお願いいたします。

#93 コマの現在地を返すAPIを作成 

---

src/resources/views/layouts/app.blade.php

🍒より先に、こちらの作業をしてしまいました...。#シャボン玉ツイートのフッターと同じデザインを実装いたしました。ご確認お願い致します。

フッターデザインの実装

---

src/app/Models/RoomLog.php

#134 room_logsテーブルのモデル作成

---

src/app/Http/Controllers/SugorokuController.php
src/app/Http/Requests/DeleteRoomRequest.php
src/public/css/app.css
src/public/js/app.js
src/resources/js/components/partials/sugoroku.vue
src/routes/api.php
src/tests/Feature/SugorokuTest.php

以下Issueの対応になります！
https://github.com/lachelier/sugoroku/issues/108

#108 部屋の削除

---

src/resources/views/auth/register.blade.php

体調の悪い時に恐縮です。「チェックが入っていない場合、「利用規約・プライバシーポリシーへの同意は必須です」というエラーを表示」がうまくいきませんでした。ご教授いただけたら幸いです。

利用規約・プライバシーポリシーへの同意を必須

---

src/resources/js/components/partials/sugoroku.vue

#149 手番中のユーザの隣にサイコロアイコンを表示

---

src/resources/js/components/partials/sugoroku.vue

お世話になっています。削除ボタンの修正をさせていただきました。ご確認、お願い致します。

削除ボタンの位置とデザイン変更

---

src/app/Http/Controllers/SugorokuController.php
src/app/Repositories/RoomRepository.php
src/tests/Feature/SugorokuTest.php

以下のIssueの対応になります。
https://github.com/lachelier/sugoroku/issues/140

#140　ウイルスが一番手の時のテスト

---

src/database/seeds/DatabaseSeeder.php

https://github.com/lachelier/sugoroku/issues/164

#164 Seederの追加

---

src/resources/js/components/partials/sugoroku.vue

#173 ゲームルールの表示の対応を行いましたので、ご確認をお願いいたします。

#173 ゲームルールの表示
